# Generated by Django 6.0.3 on 2026-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=250)),
                ('op2', models.CharField(max_length=250)),
                ('op3', models.CharField(max_length=250)),
                ('op4', models.CharField(max_length=250)),
                ('correct_ans', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('username', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
                ('mobno', models.BigIntegerField()),
            ],
        ),
    ]
