# Generated by Django 6.0.3 on 2026-03-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.EmailField(max_length=254, unique=True)),
                ('spassword', models.CharField(max_length=50)),
                ('sdepartment', models.CharField(max_length=100)),
            ],
        ),
    ]
